### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by FrancescElies**
Hi,

I removed some trailing spaces and added `palimpsest-move-region-to-top` to the Readme.
Hopefully it's fine.

Best

### CODE REVIEW

**Comment by danielsz** [comment]
Yes, this PR is fine. But yesterday's PR was not. I merged it blindly because I thought you knew what you were doing. Have you tested it before pushing?

**Comment by FrancescElies** [comment]
yes I tested, and it worked

**Comment by FrancescElies** [comment]
Sorry for the inconvenience, I remember the line being moved, I'll have to test it again

**Comment by FrancescElies** [comment]
I should have warned you I'm a begginer with elisp

**Comment by danielsz** [comment]
No problem, @FrancescElies. The truth is that I'm blaming myself for having merged without proper inspection. You thought in earnest that your code was working, so you made a beginner's mistake. Nothing wrong with that. I made assumptions out of convenience for myself. That's worse.

Anyway, the code you pushed yesterday was broken, so if something worked on your end, it was not that code.
Type `emacs -q` to have a cleand environment, `M-x load-file` and test there.

**Comment by FrancescElies** [comment]
I guess what happened is I had two functions one with point-max and the other one with point-min and once abstracted, I tested the old functions with the hard-coded definitions. Thanks for the tips

**Comment by danielsz** [comment]
Yes, that makes sense. It happens a lot in Lisp's interactive workflows. Old definitions linger around unsuspectingly and you only discover the problem after restarting the environment from a clean slate.

We both have had our lessons today. :)

**Comment by FrancescElies** [comment]
indeed 😄

**Comment by danielsz** [comment]
In the meantime, I've done some modifications that renders this PR obsolete. 

There are now customization options to set default direction (top or bottom). 

I will close this for now, but you are welcome to test the new functionality (including changing options in the customization facility).

Thank you again for contributing, @FrancescElies.

**Comment by FrancescElies** [comment]
thank you daniel

**Pull request closed without merging**
