### PR TITLE
Cesc/add tests

### PR DESCRIPTION
**Pull request by FrancescElies**
We could add some tests to the project and make them run in Travis, what do you think?
Most of this comes from drag-stuff project

### CODE REVIEW

**Comment by danielsz** [comment]
Sure, that's a good idea. 

Your PR has the setup for running tests, but doesn't run any, am I wrong?

**Comment by FrancescElies** [comment]
You need to activate the project on Travis, for my fork looks like this https://travis-ci.org/FrancescElies/Palimpsest

**Comment by FrancescElies** [comment]
Owner access is needed

**Comment by FrancescElies** [comment]
Once is activated we might need to push again to re-trigger Travis

**Comment by danielsz** [comment]
Ah, OK, I was asking where the actual tests were. They are in `features/palimpsest.feature`, correct?

Could you please add a section in the README with some explanation/instructions of how to run the tests locally? Thank you.

**Comment by FrancescElies** [comment]
I'll be inactive for at least two weeks, but I saw you comment and wanted to quickly answer your questions.

Yes you are right that's the file where tests are.

It works on travis but I did not manage to run them locally yet, I'm having some problems with `https://github.com/rejeep/evm`, but if you install it and then run the steps from the `.travis.yml` file, it should do the trick.
```
  evm install emacs-24.5 --use --skip
  cask
  make test
```
I'll add it to the readme as soon as I manage to make it work on my local environment.
Thank you.

**Comment by FrancescElies** [comment]
I added a short comment to the readme on how to run the tests, in my previous comment I did not realise evm was not actually needed in my machine to run the tests locally.

This is the output I get
```
$ make test
rm -f f.elc
cask exec ert-runner


Ran 0 tests in 0.000 seconds
cask exec ecukes
Mark set
Mark set
Moved 2 words
.

Mark set
Mark set
M.ved 2 words

2 scenarios (0 failed, 2 passed)
12 steps (0 failed, 0 skipped, 12 passed)
```

At the moment there are no unit-tests, that's why ecuckes is runnin no tests at all

Best & thanks

**Comment by FrancescElies** [comment]
Hi Daniel, I was wondering, how do you feel about this one?

**Comment by FrancescElies** [comment]
I'm closing this one, if this PR is found to be useful I'll be glad to reopen it again.

**Comment by danielsz** [comment]
Hi Francesc,

Sure, thank you.
And sorry about that.
I personally feel that CI is overkill for such a little project.

**Pull request closed without merging**
